### PR TITLE
Update spawn condition height

### PR DESCRIPTION
**Pull request by ItsAZZA**
Change the spawn condition to reflect the new world height in Minecraft 1.18

### CODE REVIEW

**Comment by NicoNekoDev** [comment]
Is better if you just check if the server is 1.17 and if not let the values 0 and 256. This way will not break compatibility with old servers.
Maybe you could also use world.getMinHeight and world.getMaxHeight instead.

**Comment by ItsAZZA** [comment]
Yes, that's an option. Although changing this in older versions won't break anything since this checks if the spawner is between these values for the spawning condition. Also need to fix current configurations with "wrong" values.

**Comment by SpraxDev** [comment]
I'd really prefer it being world dependent but here it is probably not possible.

I merged it and added a TODO line for some time later - Maybe we'll add a way to ignore the height and always assume that condition is met instead (I think in older versions like 1.8 you can increase the max build height, so vanilla spawners might work there too?)

**Comment by NicoNekoDev** [comment]
If is gonna be world dependent, you might use 'world.getMaxHeight()' as the method existed in older versions. For the new method 'world.getMinHeight()' you could add an try-catch with a silent MethodNotFoundException and if it fail just assume the min height is 0.

**Comment by SpraxDev** [comment]
Yeah probably something like that

**Pull request merged**
