### PR TITLE
giveOldEgg function

### PR DESCRIPTION
**Pull request by GKasparov**
This change is to add a function that will give the player the egg of the old mob of the spawner when they change the mob. It also adds an option in the config.yml to either enable or disable it.

### CODE REVIEW

**Comment by l3st4tDevelopment** [comment]
Unfortunately, this won't work in 1.8 as SpawnEggMeta doesn't exist in that version. Also, instead of using getConfig, you should use the Settings class.

**Comment by GKasparov** [comment]
Alright I'm looking for alternatives to SpawnEggMeta. Will try to update the commit in a bit.

**Comment by GKasparov** [comment]
Alright, feel free to check the new changes. I've changed it to use SpawnEgg which works fine on 1.8, it
's just deprecated on newer versions. Also it uses the Settings class now

**Comment by l3st4tDevelopment** [comment]
Hello, this is much better, but the use of legacy materials can be replaced with:
`ItemStack oldEgg = CompatibleMaterial.getSpawnEgg(creatureSpawner.getSpawnedType()).getItem();`
should work.

**Comment by GKasparov** [comment]
Alright I've added your simpler oldEgg

**Comment by GKasparov** [comment]
Don't merge yet there are larger changes that need to be made

**Comment by GKasparov** [comment]
https://user-images.githubusercontent.com/60962839/132295843-74b3a266-8334-42db-813c-4620e64af54a.mp4

Alright above is the Patch-1 build. It seems to be working now after testing. It's now ready.

**Pull request merged**
